import pandas as pd

def get_fever_sample(count, filename='./data_train.json', randomState=42):
    df = pd.read_json(filename)
    df["claim"] = df.apply(
        lambda row: f"{row['speaker']}: {row['claim']}" if pd.notnull(row["speaker"]) else row["claim"],
        axis=1
    )
    return df.sample(n=count, random_state=randomState)


# # Main function
# if __name__ == "__main__":
#     # Path to FEVER dataset
#     dataset_path = "fever_dataset.csv"  # Replace with your dataset path
#     fever_data = load_fever_dataset(dataset_path)
    
#     # Assuming you have a list of predictions already generated by your model
#     # Replace `your_model_predictions` with your actual predictions
#     your_model_predictions = [...]  # List of model's predictions ('SUPPORTED', 'REFUTED', 'NOT ENOUGH INFO')
    
#     if len(your_model_predictions) != len(fever_data):
#         raise ValueError("The number of predictions does not match the number of dataset entries.")
    
#     # Evaluate
#     accuracy, f1 = evaluate_model(your_model_predictions, fever_data)
    
#     print(f"Accuracy: {accuracy:.2f}")
#     print(f"F1 Score: {f1:.2f}")